apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: granted
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
spec:
  privileged: false
  allowPrivilegeEscalation: true
  requiredDropCapabilities:
  - 'SYS_ADMIN'
  volumes:
  - '*'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  readOnlyRootFilesystem: false
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
  rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
