apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: psp:granted
  rules:
- apiGroups:
  - extensions
  resourceNames:
  - granted
  resources:
  - podsecuritypolicies
  verbs:
  - use
