apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: granted
  annotations:
	seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
spec:
  privileged: false
  allowPrivilegeEscalation: true
  requiredDropCapabilities:
  - 'SYS_ADMIN'
  volumes:
  - '*'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  readOnlyRootFilesystem: false
  runAsUser:
	rule: 'RunAsAny'
  seLinux:
	rule: 'RunAsAny'
  supplementalGroups:
	rule: 'RunAsAny'
  fsGroup:
	rule: 'RunAsAny'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: psp:granted
  rules:
- apiGroups:
  - extensions
  resourceNames:
  - granted
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: psp:any:granted
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:granted
subjects:
- kind: Group
  name: system:authenticated
  apiGroup: rbac.authorization.k8s.io

